[build]
  base = "."
  publish = "website/"
  command = "cd functions && npm install && echo 'Functions ready, skipping site build'"
  functions = "functions/"

[dev]
  command = ""

[build.environment]
  PYTHON_VERSION = ""
  NODE_VERSION = "16"  # Matches package.json
