[build]
  base = "."            # Root of repo
  publish = "website/"  # Where index.html lives
  command = "echo 'Skipping build - static site with functions'"  # No build needed
  functions = "functions/"  # Serverless funcs

[dev]
  command = ""          # Optional: local dev

# Explicitly disable Python
[build.environment]
  NODE_VERSION = "16"       # Ensure Node.js for functions (16 is stable)
