[build]
  base = "."            # Root of repo
  publish = "website/"  # Where index.html lives
  command = "echo 'Skipping build - static site'"  # No build needed
  functions = "functions/"  # Serverless funcs dir

[dev]
  command = ""          # Optional: local dev

# Ensure no Python env kicks in
[build.environment]
  PYTHON_VERSION = ""   # Disable Python build
