name: Deploy Grok-beast Unleashed
on:
  push:
    branches: [main]
    paths: ['website/**']
  workflow_dispatch:  # Manual trigger option

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website
          # cname: grokbeast.xaigrokfans.com  # Optional—custom domain prep

permissions:
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: read
