name: Handle Grok-beast Feedback
on:
  workflow_dispatch:  # Manual trigger for now—simulates API call
    inputs:
      suggestion:
        description: 'User feedback from Grok-beast Unleashed'
        required: true

jobs:
  submit-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Submit Feedback as Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/xaigrokfans/grok-beast/issues \
            -d "{\"title\":\"Grok-beast Feedback\",\"body\":\"**Suggestion:** ${{ github.event.inputs.suggestion }}\n\n*Submitted via Grok-beast Unleashed*\",\"labels\":[\"feedback\"]}"
